server:
  port: 8080
spring:
  data:
    mongodb:
      uri: mongodb://mongo:27017/vedic
  kafka:
    bootstrap-servers: kafka:9092
management:
  endpoints:
    web:
      exposure:
        include: health,info
